import './global.css'
export const metadata = {
  title: 'Learning Next.js',
  description: 'Generated by Next.js',
}

export default function productLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
<body>
        {children}
  
</body>
    </html>
  )
}
