import './global.css'
import { Metadata } from 'next'
export const metadata:Metadata = {
  //object approach
  title: {
    default: 'Next js Practice Code',// default title for the site who doesnot have a specific title
    template: '%s | Next.js Practice Code',//applies to children pages
                                           // %s will be replaced by the title of the page
  },
  description: 'Generated by Next.js',
}

export default function productLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-amber-200 text-gray-800 font-sans'>
        {children}
     </body>
    </html>
  )
}
